In [1]:
!pip install sqlalchemy psycopg2-binary pandas

Requirement already satisfied: sqlalchemy in C:\Users\navin\AppData\Local\Programs\Python\Python312\Lib\site-packages (2.0.51)
Requirement already satisfied: psycopg2-binary in C:\Users\navin\AppData\Local\Programs\Python\Python312\Lib\site-packages (2.9.12)
Requirement already satisfied: pandas in C:\Users\navin\AppData\Local\Programs\Python\Python312\Lib\site-packages (3.0.3)
Requirement already satisfied: greenlet>=1 in C:\Users\navin\AppData\Local\Programs\Python\Python312\Lib\site-packages (from sqlalchemy) (3.5.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\navin\AppData\Local\Programs\Python\Python312\Lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\navin\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\navin\AppData\Roaming\Python\Python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\navin\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\navin\AppData\Roaming\Python\Python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
from sqlalchemy import create_engine
user_name= 'postgres'
password= 'Navin1430'
host= 'localhost'
port= '5432'
database = 'earthquake_db'

engine = create_engine(f'postgresql+psycopg2://{user_name}:{password}@{host}:{port}/{database}')

In [3]:
import pandas as pd

In [5]:
df=pd.read_csv('E:\earthquake_db\eq_analysis_data.csv')

<>:1: SyntaxWarning: invalid escape sequence '\e'
<>:1: SyntaxWarning: invalid escape sequence '\e'
C:\Users\navin\AppData\Local\Temp\ipykernel_27264\907906428.py:1: SyntaxWarning: invalid escape sequence '\e'
  df=pd.read_csv('E:\earthquake_db\eq_analysis_data.csv')

In [6]:
df.head(10)

,id,time,updated,latitude,longitude,depth_km,mag,place,status,alert,...,ids,sources,type,mag_type,country,year,month,day,day_of_week,depth_category
0,us6000ddi8,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.7493,-68.9337,17.27,4.70,"29 km SW of Villa Basilio Nievas, Argentina",reviewed,not available,...,",us6000ddi8,",",us,",earthquake,Moderate,Argentina,2021,1,31,Sunday,Shallow
1,us6000dev6,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.4902,-177.2052,426.71,4.10,Fiji region,reviewed,not available,...,",us6000dev6,",",us,",earthquake,Moderate,Unknown,2021,1,31,Sunday,Deep
2,us6000dev5,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.7529,121.3159,46.73,4.70,"103 km SW of Basco, Philippines",reviewed,not available,...,",us6000dev5,",",us,",earthquake,Moderate,Philippines,2021,1,31,Sunday,Shallow
3,us6000ddhs,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.1524,57.2570,10.00,4.90,"114 km N of M?n?b, Iran",reviewed,not available,...,",us6000ddhs,",",us,",earthquake,Moderate,Iran,2021,1,31,Sunday,Shallow
4,us6000dev4,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.3212,-3.7578,10.00,4.00,"184 km ENE of Olonkinbyen, Svalbard and Jan Mayen",reviewed,not available,...,",us6000dev4,",",us,",earthquake,Moderate,Svalbard and Jan Mayen,2021,1,31,Sunday,Shallow
5,pr2021031019,2021-01-31 21:34:54.690,2021-04-16 19:02:43.040,18.9996,-65.4121,46.00,3.55,"76 km NNE of Luquillo, Puerto Rico",reviewed,not available,...,",us6000ddhn,pr2021031019,",",us,pr,",earthquake,Moderate,Puerto Rico,2021,1,31,Sunday,Shallow
6,pr2021031018,2021-01-31 21:26:30.180,2021-01-31 21:52:15.880,19.0250,-65.4221,30.00,3.27,"78 km NNE of Luquillo, Puerto Rico",reviewed,not available,...,",pr2021031018,",",pr,",earthquake,Moderate,Puerto Rico,2021,1,31,Sunday,Shallow
7,pr2021031020,2021-01-31 21:14:31.020,2021-04-16 19:02:43.040,19.0436,-65.3590,28.00,3.48,"82 km N of Culebra, Puerto Rico",reviewed,not available,...,",us6000ddhc,pr2021031020,",",us,pr,",earthquake,Moderate,Puerto Rico,2021,1,31,Sunday,Shallow
8,us6000dev3,2021-01-31 20:57:55.804,2021-04-16 19:03:46.040,5.6376,126.7150,18.68,4.30,"99 km SE of Pondaguitan, Philippines",reviewed,not available,...,",us6000dev3,",",us,",earthquake,Moderate,Philippines,2021,1,31,Sunday,Shallow
9,us6000dev2,2021-01-31 20:54:42.248,2021-04-16 19:03:46.040,5.8436,126.5404,75.53,4.20,"69 km SE of Pondaguitan, Philippines",reviewed,not available,...,",us6000dev2,",",us,",earthquake,Moderate,Philippines,2021,1,31,Sunday,Deep

In [7]:
df.to_sql('earthquake_data',con=engine, if_exists='replace',index=False)

381

In [16]:
## 1. Top 10 strongest earthquakes (mag)

query="""SELECT
    id,
    place,
    mag
FROM earthquake_data
ORDER BY mag DESC
LIMIT 10;""" 
Top10_mag_df=pd.read_sql(query,engine) 
Top10_mag_df

             id                                              place  mag
0    us6000qw60        2025 Kamchatka Peninsula, Russia Earthquake  8.8
1  ak0219neiszm                    2021 Chignik, Alaska Earthquake  8.2
2    us6000f53e             2021 South Sandwich Islands Earthquake  8.1
3    us7000dflf      2021 Kermadec Islands, New Zealand Earthquake  8.1
4    us7000qx2g       140 km E of Petropavlovsk-Kamchatsky, Russia  7.8
5    us6000jllz  Pazarcik earthquake, Kahramanmaras earthquake ...  7.8
6    us7000srb1                  24 km SW of Kablalan, Philippines  7.8
7    us6000dg77                   southeast of the Loyalty Islands  7.7
8    us6000kd0n                   southeast of the Loyalty Islands  7.7
9    us7000pn9s          2025 Mandalay, Burma (Myanmar) Earthquake  7.7

In [17]:
## 2.  Top 10 deepest earthquakes (depth_km).

query="""SELECT
    id,
    place,
    depth_km
    FROM earthquake_data
ORDER BY depth_km DESC
LIMIT 10;""" 
Top10_depth_df=pd.read_sql(query,engine) 
Top10_depth_df

           id                        place  depth_km
0  us6000sp3p  206 km ENE of Sola, Vanuatu   683.578
1  us6000k2db  208 km ENE of Sola, Vanuatu   681.238
2  us7000kxdn               Vanuatu region   675.265
3  us6000mivr                  Fiji region   671.043
4  us6000rk66   205 km ESE of Levuka, Fiji   669.556
5  us6000f2w3    283 km SE of Levuka, Fiji   669.460
6  us7000q1jk     299 km E of Levuka, Fiji   667.237
7  us7000s0st   205 km ESE of Levuka, Fiji   667.197
8  us6000dhfx    south of the Fiji Islands   664.740
9  us7000he64   279 km ESE of Labasa, Fiji   664.700

In [18]:
## 3. Shallow earthquakes < 50 km and mag > 7.5
query="""SELECT place, mag, depth_km, depth_category
         FROM earthquake_data
         WHERE mag>7.5 AND depth_km<50;"""
Shallow_earthquake_df=pd.read_sql(query,engine) 
Shallow_earthquake_df

,place,mag,depth_km,depth_category
0,southeast of the Loyalty Islands,7.7,10.000,Shallow
1,"2021 Kermadec Islands, New Zealand Earthquake",8.1,28.930,Shallow
2,"2021 Chignik, Alaska Earthquake",8.2,35.000,Shallow
3,2021 South Sandwich Islands Earthquake,8.1,22.790,Shallow
4,"35 km SSW of Aguililla, Mexico",7.6,26.943,Shallow
5,"Pazarcik earthquake, Kahramanmaras earthquake ...",7.8,10.000,Shallow
6,southeast of the Loyalty Islands,7.7,18.053,Shallow
7,"19 km E of Gamut, Philippines",7.6,40.000,Shallow
8,"210 km SSW of George Town, Cayman Islands",7.6,14.326,Shallow
9,"2025 Mandalay, Burma (Myanmar) Earthquake",7.7,10.000,Shallow
10,"2025 Kamchatka Peninsula, Russia Earthquake",8.8,35.000,Shallow
11,"140 km E of Petropavlovsk-Kamchatsky, Russia",7.8,27.000,Shallow
12,Drake Passage,7.6,5.639,Shallow
13,"2025 Aomori Prefecture, Japan Earthquake",7.6,40.720,Shallow

In [46]:
## 4. Average depth per continent.
query="""SELECT country, AVG(depth_km) as average_depth
         FROM earthquake_data
         GROUP BY country
         ORDER BY average_depth DESC;"""
Average_depth_df=pd.read_sql(query,engine) 
Average_depth_df

               country  average_depth
0          North Korea     577.230750
1                 Fiji     519.801824
2               Brazil     288.024241
3             Malaysia     275.055143
4    Wallis and Futuna     274.895257
..                 ...            ...
226            Wyoming       0.469313
227     North Carolina       0.100000
228          Minnesota       0.000000
229               Iowa       0.000000
230         Indonesia        0.000000

[231 rows x 2 columns]

In [ ]:
## 5. Average magnitude per magnitude type (magType)
query="""SELECT mag_type, AVG(mag) as average_magnitude
         FROM earthquake_data
         GROUP BY mag_type
         ORDER BY average_magnitude DESC;"""
Average_mag_df=pd.read_sql(query,engine) 
Average_mag_df

      mag_type  average_magnitude
0  Destructive           7.326506
1       Strong           5.305461
2     Moderate           4.151076

Time Analysis

In [21]:
## 6. Year with most earthquakes.

query="""SELECT year,count(type) as most_eq
            FROM earthquake_data
            GROUP BY year
            LIMIT 1;"""
year_most_eq_df=pd.read_sql(query,engine)
year_most_eq_df

   year  most_eq
0  2024    18659

In [52]:
## 7. Month with highest number of earthquakes.

query="""SELECT month,count(type) as most_eq
            FROM earthquake_data
            GROUP BY month
            ORDER BY most_eq DESC
            LIMIT 1;"""
month_most_eq_df=pd.read_sql(query,engine)
month_most_eq_df

   month  most_eq
0      3    10906

In [23]:
## 8. Day of week with most earthquakes.

query="""SELECT day_of_week,count(type) as most_eq
            FROM earthquake_data
            GROUP BY day_of_week
            LIMIT 1;"""
DOW_most_eq_df=pd.read_sql(query,engine)
DOW_most_eq_df

  day_of_week  most_eq
0     Tuesday    16477

In [ ]:
## 9. Count of earthquakes per hour of day.

query="""SELECT
        EXTRACT(HOUR FROM CAST("time" AS TIMESTAMP)) AS hour_of_day,
        COUNT(*) AS earthquake_count
        FROM earthquake_data
        GROUP BY hour_of_day
        ORDER BY hour_of_day;"""

count_hr_df=pd.read_sql(query,engine)
count_hr_df

    hour_of_day  earthquake_count
0           0.0              4721
1           1.0              4980
2           2.0              4830
3           3.0              5050
4           4.0              5000
5           5.0              4660
6           6.0              4583
7           7.0              4728
8           8.0              4720
9           9.0              4693
10         10.0              4553
11         11.0              4472
12         12.0              4433
13         13.0              4683
14         14.0              4539
15         15.0              4670
16         16.0              4579
17         17.0              4705
18         18.0              4761
19         19.0              4802
20         20.0              4821
21         21.0              5025
22         22.0              4909
23         23.0              4713

In [24]:
## 10. Most active reporting network (net).

query="""SELECT net,count(net) as most_reported
        FROM earthquake_data
        GROUP BY net
        ORDER BY most_reported DESC
        LIMIT 1;"""
most_rep_net_df=pd.read_sql(query,engine)
most_rep_net_df

  net  most_reported
0  us          99850

Casualities and Economic loss

In [ ]:
## 11. top 5 highest casualties
## since there is no column as "casualities" taking top 5 as per mag 

query="""SELECT
    place,mag,
    sig,depth_km
    FROM earthquake_data
    ORDER BY mag DESC
    LIMIT 5;"""
high_casualtites_df=pd.read_sql(query,engine)
high_casualtites_df

                                               place  mag   sig  depth_km
0        2025 Kamchatka Peninsula, Russia Earthquake  8.8  2114     35.00
1                    2021 Chignik, Alaska Earthquake  8.2  1500     35.00
2             2021 South Sandwich Islands Earthquake  8.1  1009     22.79
3      2021 Kermadec Islands, New Zealand Earthquake  8.1  1021     28.93
4  Pazarcik earthquake, Kahramanmaras earthquake ...  7.8  2910     10.00

In [43]:
### 12. since there is no columns as economic loss or damages, taking the mag and sig 

query="""SELECT
        alert,
        AVG(mag) AS avg_magnitude,
        AVG(sig) AS avg_significance,
        COUNT(*) AS earthquake_count
        FROM earthquake_data
        WHERE alert IS NOT NULL
        GROUP BY alert
        ORDER BY avg_significance DESC;"""

ECloss_df=pd.read_sql(query,engine)
ECloss_df

           alert  avg_magnitude  avg_significance  earthquake_count
0            red       6.738462       2303.192308                26
1         orange       6.316000       1184.640000                25
2         yellow       6.012879        809.401515               132
3          green       5.380903        480.537606              4494
4  not available       4.206939        278.310650            109554

In [27]:
##14.  Count of reviewed vs automatic earthquakes (status)

query="""SELECT status, COUNT(status) as count
            FROM earthquake_data
            GROUP BY status;"""
count_RvA_df=pd.read_sql(query,engine)
count_RvA_df

      status   count
0   reviewed  114059
1  automatic     172

In [28]:
##15.  Count by earthquake type (type).
query="""SELECT type, COUNT(type) as count
            FROM earthquake_data
            GROUP BY type
            ORDER BY count DESC;"""
count_type_df=pd.read_sql(query,engine)
count_type_df

                     type   count
0              earthquake  113360
1        mining explosion     828
2               ice quake      13
3       volcanic eruption      12
4             other event       5
5               landslide       4
6  experimental explosion       3
7           mine collapse       3
8            quarry blast       2
9               explosion       1

In [29]:
## 16. Number of earthquakes by data type (types)
query="""SELECT
    TRIM(unnest(string_to_array(types, ','))) AS type_name,
    COUNT(types) AS count
    FROM earthquake_data
    WHERE types is not null
    GROUP BY type_name
    ORDER BY count DESC;"""
count_types_df=pd.read_sql(query,engine)
count_types_df

                 type_name   count
0                           228462
1                   origin  114231
2               phase-data  114213
3                     dyfi   17492
4                 shakemap    9863
5            moment-tensor    8719
6                losspager    4677
7   internal-moment-tensor    4532
8          earthquake-name    2818
9            nearby-cities    1950
10            scitech-link    1911
11         internal-origin    1785
12         focal-mechanism    1396
13             impact-text    1052
14          ground-failure     958
15             impact-link     659
16             shake-alert     387
17                     oaf     246
18               associate     218
19          event-sequence     161
20            general-text     146
21            finite-fault      70
22     groundmotion-packet      57
23            trump-origin      23
24            disassociate      20
25            general-link      13
26          general-header      12
27            significance       6
28          trump-shakemap       3
29         losspager-admin       3
30    trump-ground-failure       3
31     trump-moment-tensor       2
32         trump-losspager       1
33     internal-phase-data       1

In [30]:
 ##17. Average RMS and gap per continent

query="""SELECT country, AVG(rms)AS avg_rms,
       AVG(gap)AS avg_gap
FROM earthquake_data
GROUP BY country
ORDER BY avg_rms , avg_gap DESC
LIMIT 20;"""

Avg_rms_gap_df=pd.read_sql(query,engine)
Avg_rms_gap_df

                  country   avg_rms     avg_gap
0                      NV  0.085217   87.434783
1              Indonesia   0.090000  113.000000
2        Texas Earthquake  0.100000   38.000000
3       Nevada Earthquake  0.116300  105.000000
4                  Hawaii  0.140986  140.998928
5                  Nevada  0.161868   99.605442
6                   Texas  0.177312   63.342105
7                Arkansas  0.180000   57.666667
8                      CA  0.185245   89.523868
9                      WA  0.200000   26.000000
10               Oklahoma  0.209539   54.311828
11               Missouri  0.216667   40.333333
12  California Earthquake  0.230000  229.000000
13         American Samoa  0.250000  259.716312
14              Tennessee  0.258750   41.750000
15            Puerto Rico  0.264948  230.792540
16             New Mexico  0.267752   68.035971
17                     MX  0.273822  116.455497
18                   Iowa  0.275000   51.000000
19               Illinois  0.276000   47.600000

In [31]:
 ##18. Events with high station coverage 
query="""SELECT country, nst
        FROM earthquake_data
        ORDER BY nst DESC
        LIMIT 15;"""
high_coverage_df=pd.read_sql(query,engine)
high_coverage_df

                   country    nst
0                    Japan  619.0
1                   Russia  566.0
2                   Alaska  516.0
3                  Unknown  475.0
4                Argentina  466.0
5                  Unknown  452.0
6                  Unknown  444.0
7   Svalbard and Jan Mayen  437.0
8                   Alaska  437.0
9              Afghanistan  423.0
10                  Russia  420.0
11       Alaska Earthquake  410.0
12                   Tonga  406.0
13                 Unknown  402.0
14             Philippines  401.0

In [ ]:
## 19. Number of tsunamis triggered per year.

In [34]:
## 20.Count earthquakes by alert levels (red, orange, etc.)
query="""SELECT alert, COUNT(alert) as EQ_count
         FROM earthquake_data
         WHERE type = 'earthquake'
         GROUP BY alert
         ORDER BY EQ_count DESC;"""
count_alert_df=pd.read_sql(query,engine)
count_alert_df

           alert  eq_count
0  not available    108683
1          green      4494
2         yellow       132
3            red        26
4         orange        25

In [35]:
##21.Find the top 5 countries with 
# the highest average magnitude of earthquakes in the past 5 years 

query="""SELECT country, ROUND(CAST(AVG(mag)AS numeric),2) AS avg_mag
        FROM earthquake_data
        WHERE year BETWEEN 2021 AND 2026
        GROUP BY country
        ORDER BY avg_mag DESC
        LIMIT 5;"""
top5_hig_mag_df=pd.read_sql(query,engine)
top5_hig_mag_df

                             country  avg_mag
0             New Zealand Earthquake     8.10
1                  Russia Earthquake     8.10
2         Burma (Myanmar) Earthquake     7.70
3  Kahramanmaras earthquake sequence     7.65
4                  Alaska Earthquake     7.57

In [36]:
##.22.Find countries that have experienced both shallow and deep earthquakes within the same month
query="""SELECT country,
                month,
                SUM(CASE WHEN depth_category = 'Shallow' THEN 1 ELSE 0 END) AS shallow_count,
                SUM(CASE WHEN depth_category = 'Deep' THEN 1 ELSE 0 END) AS deep_count
        FROM earthquake_data
        WHERE depth_category IN ('Shallow', 'Deep')
        GROUP BY country, month
        HAVING COUNT(DISTINCT depth_category) = 2
        ORDER BY country, month;"""

SD_month_df=pd.read_sql(query,engine)
SD_month_df

               country  month  shallow_count  deep_count
0          Afghanistan      1             17          72
1          Afghanistan      2             17          74
2          Afghanistan      3             11          77
3          Afghanistan      4             12          55
4          Afghanistan      5             13          73
..                 ...    ...            ...         ...
545  Wallis and Futuna      8              1          14
546  Wallis and Futuna      9              3          10
547  Wallis and Futuna     10              3           8
548  Wallis and Futuna     11              6          20
549  Wallis and Futuna     12              8          12

[550 rows x 4 columns]

In [37]:
##23.Compute the year-over-year growth rate in the total number of earthquakes globally.

query="""WITH yearly_counts AS (
    SELECT year,
           COUNT(*) AS total_earthquakes
    FROM earthquake_data
    GROUP BY year
)
SELECT year,
       total_earthquakes,
       ROUND(
           (
             (total_earthquakes -
              LAG(total_earthquakes) OVER (ORDER BY year)
             ) * 100.0
           ) /
           LAG(total_earthquakes) OVER (ORDER BY year),
           2
       ) AS yoy_growth_rate
FROM yearly_counts
ORDER BY year;"""

yoy_rate_df=pd.read_sql(query,engine)
yoy_rate_df

   year  total_earthquakes  yoy_growth_rate
0  2021              21926              NaN
1  2022              20208            -7.84
2  2023              20830             3.08
3  2024              18659           -10.42
4  2025              22818            22.29
5  2026               9790           -57.10

In [38]:
##24. List the 3 most seismically active regions by combining both frequency and average magnitude

query="""SELECT place,
       COUNT(*) AS earthquake_count,
       ROUND(AVG(mag)::numeric,2) AS avg_mag,
       ROUND((COUNT(*) * AVG(mag))::numeric,2) AS activity_score
FROM earthquake_data
GROUP BY place
ORDER BY activity_score DESC
LIMIT 3;"""

Top3_active_df=pd.read_sql(query,engine)
Top3_active_df

                           place  earthquake_count  avg_mag  activity_score
0  South Sandwich Islands region              3128     4.68        14640.26
1        Kermadec Islands region              1925     4.64         8941.37
2      south of the Fiji Islands              2001     4.44         8893.00

In [39]:
##25. For each country, calculate the average depth of earthquakes within ±5° latitude range of the equator.

query="""SELECT country,
                ROUND(AVG(depth_km)::numeric,2) AS avg_depth
        FROM earthquake_data
        WHERE latitude BETWEEN -5 AND 5
        GROUP BY country
        ORDER BY avg_depth DESC;"""
ctry_avg_depth_df=pd.read_sql(query,engine)
ctry_avg_depth_df

                             country  avg_depth
0                        Philippines     116.85
1                   Papua New Guinea      71.43
2                               Peru      63.98
3                            Ecuador      62.70
4                          Indonesia      62.45
5                           Colombia      41.78
6                            Unknown      23.39
7                       Congo-Uganda      14.78
8                          Venezuela      11.13
9                           Malaysia      10.76
10                            Brazil      10.56
11                            Rwanda      10.44
12                            Guyana      10.35
13                            Uganda      10.08
14                          Tanzania      10.00
15                           Burundi      10.00
16                   Kiribati region      10.00
17                             Palau      10.00
18                          Ethiopia      10.00
19                            Panama      10.00
20                       South Sudan      10.00
21                    Ecuador region       9.99
22  Democratic Republic of the Congo       9.92
23                             Gabon       9.82
24                             Kenya       9.80

In [40]:
## 26. Identify countries having the highest ratio of shallow to deep earthquakes.

query="""SELECT country,
       COUNT(CASE WHEN depth_category='Shallow' THEN 1 END) AS shallow_count,
       COUNT(CASE WHEN depth_category='Deep' THEN 1 END) AS deep_count,
       ROUND(
           COUNT(CASE WHEN depth_category='Shallow' THEN 1 END)::numeric /
           NULLIF(COUNT(CASE WHEN depth_category='Deep' THEN 1 END),0),
           2
       ) AS shallow_deep_ratio
FROM earthquake_data
GROUP BY country
ORDER BY shallow_deep_ratio DESC NULLS LAST
LIMIT 25;"""

ctry_highest_ratio_df=pd.read_sql(query,engine)
ctry_highest_ratio_df

                country  shallow_count  deep_count  shallow_deep_ratio
0                Hawaii            932           1              932.00
1                  Iran            965           3              321.67
2                Canada            287           1              287.00
3                Panama            220           2              110.00
4                 Nepal            146           2               73.00
5                 China           1375          19               72.37
6               Morocco             64           1               64.00
7                Turkey            958          16               59.88
8              Pakistan            234           5               46.80
9          India region            146           4               36.50
10               Cyprus             36           1               36.00
11  Antigua and Barbuda             33           1               33.00
12               Greece           1422          45               31.60
13           Micronesia            147           5               29.40
14               Taiwan           1011          35               28.89
15                Spain             28           1               28.00
16        New Caledonia            299          11               27.18
17           Costa Rica            179          10               17.90
18             Honduras             69           4               17.25
19  U.S. Virgin Islands           1399         151                9.26
20             Anguilla            106          12                8.83
21           Guadeloupe             67           8                8.38
22          Puerto Rico           2837         407                6.97
23               Russia           5323         919                5.79
24                India            622         111                5.60

In [44]:
query="""SELECT
    ROUND(AVG(CASE WHEN tsunami = 1 THEN mag END)::numeric, 2) AS tsunami_avg_mag,
    ROUND(AVG(CASE WHEN tsunami = 0 THEN mag END)::numeric, 2) AS non_tsunami_avg_mag,
    ROUND(
        (
            AVG(CASE WHEN tsunami = 1 THEN mag END) -
            AVG(CASE WHEN tsunami = 0 THEN mag END)
        )::numeric,
        2
    ) AS magnitude_difference
FROM earthquake_data;"""

tsunami_avgdiff_df=pd.read_sql(query,engine)
tsunami_avgdiff_df

  tsunami_avg_mag non_tsunami_avg_mag magnitude_difference
0            None                None                 None

In [41]:
##Using the gap and rms columns, 
# identify events with the lowest data reliability (highest average error margins).

query="""SELECT id,
       place,
       gap,
       rms,
       ROUND((gap * rms)::numeric,2) AS reliability_score
FROM earthquake_data
ORDER BY reliability_score DESC
LIMIT 20;"""

low_data_rlbty_df=pd.read_sql(query,engine)
low_data_rlbty_df

,id,place,gap,rms,reliability_score
0,aka2026mirxwc,"232 km ESE of Attu Station, Alaska",341.000000,1.800000,613.80
1,ak2025xgbuwx,"Rat Islands, Aleutian Islands, Alaska",333.434784,1.830562,610.37
2,aka2026hogxjn,"26 km WSW of Pelican, Alaska",122.000000,3.400000,414.80
3,us7000dhvp,"185 km NE of Gisborne, New Zealand",289.000000,1.360000,393.04
4,us6000p70f,"48 km E of Port-Olry, Vanuatu",283.000000,1.320000,373.56
5,ci40332296,"148km SSE of Estacion Coahuila, B.C., MX",217.000000,1.710000,371.07
6,us7000dinz,"193 km NE of Gisborne, New Zealand",299.000000,1.240000,370.76
7,us6000q3zc,Kermadec Islands region,270.000000,1.350000,364.50
8,aka2026mamwqv,"224 km SSW of Nikolski, Alaska",259.000000,1.400000,362.60
9,us6000r05v,"286 km SSE of Attu Station, Alaska",341.000000,1.060000,361.46
10,us6000eqvb,south of the Kermadec Islands,255.000000,1.410000,359.55
11,us6000r287,"39 km N of Chamba, India",269.000000,1.330000,357.77
12,us7000p9s7,"79 km SE of Atka, Alaska",315.000000,1.130000,355.95
13,ak2026cionbw,"68 km ESE of Sand Point, Alaska",221.000000,1.600000,353.60
14,us7000e4cp,"14 km S of La Rivera, Mexico",248.000000,1.420000,352.16
15,aka2026micuzf,"180 km E of Atka, Alaska",206.000000,1.700000,350.20
16,us6000f42a,"132 km SE of Atka, Alaska",311.000000,1.120000,348.32
17,us7000lwpb,"72 km SSW of Islay (Matarani), Peru",249.000000,1.390000,346.11
18,us6000pmll,"156 km SSW of Puerto San José, Guatemala",247.000000,1.400000,345.80
19,us7000dk8u,"Kermadec Islands, New Zealand",260.000000,1.330000,345.80

In [42]:
## 30.Determine the regions with the highest frequency of deep-focus earthquakes (depth > 300 km).

query="""SELECT country,
       COUNT(*) AS deep_focus_count
FROM earthquake_data
WHERE depth_km > 300
GROUP BY country
ORDER BY deep_focus_count DESC;"""
highfrq_region_df=pd.read_sql(query,engine)
highfrq_region_df

                     country  deep_focus_count
0                    Unknown              3299
1                       Fiji              1201
2                      Tonga               606
3                  Indonesia               287
4               Japan region               249
5                Timor Leste               213
6          Wallis and Futuna               167
7   Northern Mariana Islands               129
8                      Japan               127
9                Philippines               121
10                    Russia               100
11          Papua New Guinea                77
12                 Argentina                37
13                   Vanuatu                28
14                   Bolivia                21
15                    Brazil                14
16                     Italy                13
17               New Zealand                11
18           Solomon Islands                 8
19               North Korea                 4
20                  Malaysia                 3
21                      Peru                 1
22               Afghanistan                 1
23                     China                 1
24                      Guam                 1